package com.winteam.language.customerservice;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Customer")
public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "First Name")
   private java.lang.String firstname;
   @org.kie.api.definition.type.Label(value = "Last Name")
   private java.lang.String lastName;
   @org.kie.api.definition.type.Label(value = "Address")
   private com.winteam.language.customerservice.Address address;

   public Customer()
   {
   }

   public java.lang.String getFirstname()
   {
      return this.firstname;
   }

   public void setFirstname(java.lang.String firstname)
   {
      this.firstname = firstname;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public com.winteam.language.customerservice.Address getAddress()
   {
      return this.address;
   }

   public void setAddress(com.winteam.language.customerservice.Address address)
   {
      this.address = address;
   }

   public Customer(java.lang.String firstname, java.lang.String lastName,
         com.winteam.language.customerservice.Address address)
   {
      this.firstname = firstname;
      this.lastName = lastName;
      this.address = address;
   }

    public String toString() {
		return "Customer [firstname=" + firstname + ", lastname=" + lastname
				+ ", address=" + address;
	}
}