package com.winteam.language.customerservice;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Wes")
   private java.lang.String firstname;
   @org.kie.api.definition.type.Label(value = "Wes")
   private java.lang.String lastname;
   @org.kie.api.definition.type.Label(value = "Wes")
   private com.winteam.language.customerservice.Address address;

   public Customer()
   {
   }

   public java.lang.String getFirstname()
   {
      return this.firstname;
   }

   public void setFirstname(java.lang.String firstname)
   {
      this.firstname = firstname;
   }

   public java.lang.String getLastname()
   {
      return this.lastname;
   }

   public void setLastname(java.lang.String lastname)
   {
      this.lastname = lastname;
   }

   public com.winteam.language.customerservice.Address getAddress()
   {
      return this.address;
   }

   public void setAddress(com.winteam.language.customerservice.Address address)
   {
      this.address = address;
   }

   public Customer(java.lang.String firstname, java.lang.String lastname,
         com.winteam.language.customerservice.Address address)
   {
      this.firstname = firstname;
      this.lastname = lastname;
      this.address = address;
   }
   
   public String toString() {
		return "Customer [firstName=" + firstName + ", lastName=" + lastName
				+ ", address=" + address + "]";
       
   }

}