package com.winteam.language;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerService implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CustomerService() {
    }

}